imagePath: "cognetive/network_stresser:0.0.2"
imagePullPolicy: IfNotPresent
serviceName: receiver
receiverReplicas: 2
generatorReplicas: 3
imageConfig:
  pythonPath: /usr/bin/python2.7
  generatorPath: /usr/bin/traffic_generator.py
  receiverPath: /usr/bin/traffic_receiver.py
  tcpReceiverPath: /usr/bin/traffic_receiver_tcp.py
  udpReceiverPath: /usr/bin/traffic_receiver_udp.py
cmdOptions:
  tcpPort: 80
  udpPort: 8080
  udpPercentage: 50
  minBytes: 100
  maxBytes: 1000
  udpBuffer: 2000
  numOfFlows: 20
  time: 5
  delay: 50
  silent: False
  