apiVersion: v1
kind: Service
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  type: ClusterIP
  ports:
  - name: tcp-receiver
    protocol: TCP
    port: {{ .Values.cmdOptions.tcpPort }}
    targetPort: {{ .Values.cmdOptions.tcpPort }}
  - name: udp-receiver
    protocol: UDP
    port: {{ .Values.cmdOptions.udpPort }}
    targetPort: {{ .Values.cmdOptions.udpPort }}
  selector:
    app: receiver
